### ISSUE TITLE
Any plans for conditional flow blocks?

### ISSUE THREAD

**Issue by joshbedo** [alyssaxuu/flowy#64] opened 2020-05-05 01:39 UTC
This would be super useful for routing logic. For example

1. new lead
2. if new lead has tag X do this else do this.

If not I'd be open to brainstorming something and possibly submitting a PR or something :)

**Comment by jamessampford** [comment] 2020-05-05 07:20
A block (new lead) can have multiple children, so one child block can be if tag = X and the other child block can be if tag != X

**Comment by joshbedo** [comment] 2020-05-05 08:02
Great! makes sense excited to start building this out connect it with a job queue

**Comment by johndkn** [comment] 2020-05-05 13:50
Hi @joshbedo,
This is also being discussed here : #29 :)

**Comment by alyssaxuu** [comment] 2020-05-15 23:20
Closing issue as it is a duplicate of #29.

**Closed by alyssaxuu** 2020-05-15 23:20 UTC
Labels: duplicate
