### ISSUE TITLE
expose rearrangeMe

### ISSUE THREAD

**Issue by taf2** [alyssaxuu/flowy#33] opened 2020-01-02 17:45 UTC
It might be nice to expose rearrangeMe - or call this when importing.  It's not always possible to export and then import exactly the same data.   so for example if migrating from an existing data-structure to flowy it would be nice to not need the html part of output when calling import.

**Comment by alyssaxuu** [comment] 2020-01-06 12:02
How do you mean? The rearrangeMe function is used when snapping a particular block (so when you drag a block, bring it close to a parent, and then release), so I'm not sure what it would have to do with the import functionality of Flowy.

HTML part is necessary because Flowy doesn't have a "default" UI, so blocks might be different. If you mean being able to simply import properties instead of the HTML and then use those to automatically generate the blocks using your own "block template", then that's something else. Not sure how it could be implemented exactly, but I suppose it could be a useful feature.

**Comment by Jisco** [comment] 2020-03-27 13:02
Duplicate of #40

**Comment by alyssaxuu** [comment] 2020-04-03 16:27
Now calling rearrangeMe on import.

**Closed by alyssaxuu** 2020-04-03 16:27 UTC
Labels: question
